on:
  push:
    branches:
      main
name: Render
jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    container: geocompr/geocompr:minimal
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
             any::rcmdcheck
             any::pkgdown
          needs: check

      - uses: r-lib/actions/check-r-package@v2

      - name: Install package
        run: R CMD INSTALL .

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
